services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: development
      DB_NAME: mydb
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: development
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"